#!/usr/bin/perl

# Eighth finger of taiga bear v0.2.2
# By Kurashov A.K. License - GNU GPLv3.
#
# Fix cyrillic letters typed in the wrong layout
# Reads from stdin and puts to stdout in UTF-8 encoding

use utf8;
# char arrays
@wlatin = ("q", "Q", "w", "W", "e", "E", "r", "R", "t", "T", "y", "Y", "u", "U", "i", "I", "o", "O", "p", "P", "\\\[", "\\\{", "\\\]", "\\\}", "a", "A", "s", "S", "d", "D", "f", "F", "g", "G", "h", "H", "j", "J", "k", "K", "l", "L", "\\\;", ":", "\'", "\"", "z", "Z", "x", "X", "c", "C", "v", "V", "b", "B", "n", "N", "m", "M", ",", "<", "\\\.", ">", "`", "~");
@rrussian = ("й", "Й", "ц", "Ц", "у", "У", "к", "К", "е", "Е", "н", "Н", "г", "Г", "ш", "Ш", "щ", "Щ", "з", "З", "х", "Х", "ъ", "Ъ", "ф", "Ф", "ы", "Ы", "в", "В", "а", "А", "п", "П", "р", "Р", "о", "О", "л", "Л", "д", "Д", "ж", "Ж", "э", "Э", "я", "Я", "ч", "Ч", "с", "С", "м", "М", "и", "И", "т", "Т", "ь", "Ь", "б", "Б", "ю", "Ю", "ё", "Ё");

# read stdin
while (defined($textforfix = <STDIN>)) {
# fix chars
for($char_indx = 0; $char_indx < scalar @wlatin; $char_indx++) { $textforfix =~ s/$wlatin[$char_indx]/$rrussian[$char_indx]/g; }
# put fixed text to stdout
binmode STDOUT, ':utf8';
print "$textforfix";
}
